
import type { Product, Order, AdminUser } from './types';

export const placeholderAdminUsers: AdminUser[] = [
  {
    id: 'su1',
    username: 'Eden',
    passwordHash: '0544808850',
    isSuperAdmin: true,
    displayName: 'סוכן עדן',
  },
];

export let placeholderProducts: Product[] = [
  // נוזלי כביסה (כולל מוצרי Bio לשעבר)
  {
    id: 'kbio1',
    name: 'כביסכל Bio אלגנס – 2 ליטר',
    description: 'נוזל כביסה Bio איכותי בניחוח אלגנס עדין. 2 ליטר.',
    price: 43.00,
    imageUrl: '/images/products/kbio1.jpeg',
    dataAiHint: 'bio elegance',
    category: 'נוזלי כביסה',
    isActive: true,
  },
  {
    id: 'kbio2',
    name: 'כביסכל Bio ספורט 2 ליטר',
    description: 'נוזל כביסה Bio מותאם לבגדי ספורט, מנטרל ריחות. 2 ליטר.',
    price: 45.00,
    imageUrl: '/images/products/kbio2.jpeg',
    dataAiHint: 'bio sport',
    category: 'נוזלי כביסה',
    isActive: true,
  },
  {
    id: 'kbio3',
    name: 'כביסכל Bio סופט קייר 2 ליטר',
    description: 'נוזל כביסה Bio עדין במיוחד, מתאים לבעלי עור רגיש. 2 ליטר.',
    price: 43.00,
    imageUrl: '/images/products/kbio3.jpeg',
    dataAiHint: 'bio soft',
    category: 'נוזלי כביסה',
    isActive: true,
  },
  {
    id: 'kbio4',
    name: 'כביסכל Bio פרידום – 2 ליטר',
    description: 'נוזל כביסה Bio בניחוח מרענן של חופש. 2 ליטר.',
    price: 43.00,
    imageUrl: '/images/products/kbio4.jpeg',
    dataAiHint: 'bio freedom',
    category: 'נוזלי כביסה',
    isActive: true,
  },
  {
    id: 'kbio5',
    name: 'כביסכל Bio אוריינטל – 2 ליטר',
    description: 'נוזל כביסה Bio בניחוח אוריינטלי עשיר ומפנק. 2 ליטר.',
    price: 43.00,
    imageUrl: '/images/products/kbio5.jpeg',
    dataAiHint: 'bio oriental',
    category: 'נוזלי כביסה',
    isActive: true,
  },
  {
    id: 'kbio6',
    name: 'כביסכל Bio ספא – 2 ליטר',
    description: 'נוזל כביסה Bio בניחוח ספא מרגיע ויוקרתי. 2 ליטר.',
    price: 43.00,
    imageUrl: '/images/products/kbio6.jpeg',
    dataAiHint: 'bio spa',
    category: 'נוזלי כביסה',
    isActive: true,
  },
  {
    id: 'kbio7',
    name: 'כביסכל Bio בייבי – 2 ליטר',
    description: 'נוזל כביסה Bio היפואלרגני, מותאם במיוחד לבגדי תינוקות. 2 ליטר.',
    price: 43.00,
    imageUrl: '/images/products/kbio7.jpeg',
    dataAiHint: 'bio baby',
    category: 'נוזלי כביסה',
    isActive: true,
  },
  {
    id: 'kbio8',
    name: 'כביסכל Bio מאסק פלאורס – 2 ליטר',
    description: 'נוזל כביסה Bio בניחוח מאסק ופרחים משולב. 2 ליטר.',
    price: 43.00,
    imageUrl: '/images/products/kbio8.jpeg',
    dataAiHint: 'bio musk flowers',
    category: 'נוזלי כביסה',
    isActive: true,
  },
  {
    id: 'kbio9',
    name: 'כביסכל Bio רוז – 2 ליטר',
    description: 'נוזל כביסה Bio בניחוח ורדים קלאסי ורומנטי. 2 ליטר.',
    price: 43.00,
    imageUrl: '/images/products/kbio9.jpeg',
    dataAiHint: 'bio rose',
    category: 'נוזלי כביסה',
    isActive: true,
  },
  {
    id: 'kbio10',
    name: 'כביסכל Bio ארומטי- 2 ליטר',
    description: 'נוזל כביסה Bio בניחוח ארומטי ועשיר. 2 ליטר.',
    price: 43.00,
    imageUrl: '/images/products/kbio10.jpeg',
    dataAiHint: 'bio aromatic',
    category: 'נוזלי כביסה',
    isActive: true,
  },
  {
    id: 'kbio11',
    name: 'כביסכל Bio רד רוז – 2 ליטר',
    description: 'נוזל כביסה Bio בניחוח ורד אדום עמוק. 2 ליטר.',
    price: 43.00,
    imageUrl: '/images/products/kbio11.jpeg',
    dataAiHint: 'bio red rose',
    category: 'נוזלי כביסה',
    isActive: true,
  },
  {
    id: 'kcat7',
    name: 'נוזל כביסה קלאסי "כביסכל"',
    description: 'נוזל כביסה לשימוש יומיומי, יעיל וחסכוני לכל סוגי הבדים.',
    price: 35.00,
    imageUrl: '/images/products/kcat7.png',
    dataAiHint: 'classic laundry',
    category: 'נוזלי כביסה',
    isActive: true,
  },

  // חבילות
  {
    id: 'pkg1',
    name: 'מארז חבילה מוגדלת',
    description: 'מארז חבילה מוגדלת הכולל מגוון מוצרים.',
    price: 324.00,
    imageUrl: '/images/products/pkg1.webp',
    dataAiHint: 'large bundle',
    category: 'חבילות',
    isActive: true,
  },
  {
    id: 'pkg2',
    name: 'מארזי יוקרה',
    description: 'מארזי יוקרה מפנקים.',
    price: 95.00,
    imageUrl: '/images/products/pkg2.webp',
    dataAiHint: 'luxury bundle',
    category: 'חבילות',
    isActive: true,
  },
  {
    id: 'pkg3',
    name: 'מארז חבילות',
    description: 'מארז חבילות משתלם במיוחד.',
    price: 199.00,
    imageUrl: '/images/products/pkg3.webp',
    dataAiHint: 'package bundle',
    category: 'חבילות',
    isActive: true,
  },
  {
    id: 'pkg4',
    name: 'מארז מאסק פלווארס',
    description: 'מארז בניחוח מאסק פלווארס הכולל מוצרים נבחרים.',
    price: 130.00,
    imageUrl: '/images/products/pkg4.jpeg',
    dataAiHint: 'musk flowers bundle',
    category: 'חבילות',
    isActive: true,
  },
  {
    id: 'pkg5',
    name: 'חבילת מפיצי ריח ביו בניחוחות כביסכל',
    description: 'חבילה מרוכזת של מפיצי ריח Bio בניחוחות האהובים של כביסכל.',
    price: 259.00,
    imageUrl: '/images/products/pkg5.jpg',
    dataAiHint: 'bio diffuser bundle',
    category: 'חבילות',
    isActive: true,
  },
  {
    id: 'pkg6',
    name: 'מארז נבחרת מוצרי הניקיון',
    description: 'מארז הכולל את נבחרת מוצרי הניקיון המקצועיים שלנו.',
    price: 240.00,
    imageUrl: '/images/products/pkg6.jpg',
    dataAiHint: 'cleaning bundle',
    category: 'חבילות',
    isActive: true,
  },
  {
    id: 'pkg7',
    name: 'מארז חבילת בייבי',
    description: 'מארז חבילת בייבי מפנק. המחיר עשוי להשתנות לפי אפשרויות.',
    price: 160.00,
    imageUrl: '/images/products/pkg7.jpeg',
    dataAiHint: 'baby bundle',
    category: 'חבילות',
    isActive: true,
  },
  {
    id: 'pkg8',
    name: 'מארז חבילת רוז',
    description: 'מארז חבילת רוז בניחוח קלאסי. המחיר עשוי להשתנות לפי אפשרויות.',
    price: 160.00,
    imageUrl: '/images/products/pkg8.jpeg',
    dataAiHint: 'rose bundle',
    category: 'חבילות',
    isActive: true,
  },
  {
    id: 'pkg9',
    name: 'מארז חבילת ארומטי',
    description: 'מארז חבילת ארומטי בניחוח עשיר. המחיר עשוי להשתנות לפי אפשרויות.',
    price: 160.00,
    imageUrl: '/images/products/pkg9.jpeg',
    dataAiHint: 'aromatic bundle',
    category: 'חבילות',
    isActive: true,
  },
  {
    id: 'pkg10',
    name: 'מארז חבילת רד רוז',
    description: 'מארז חבילת רד רוז בניחוח עמוק וחושני.',
    price: 130.00,
    imageUrl: '/images/products/pkg10.jpeg',
    dataAiHint: 'red rose bundle',
    category: 'חבילות',
    isActive: true,
  },
  {
    id: 'pkg11',
    name: 'מארז חבילת ספא',
    description: 'מארז חבילת ספא יוקרתי. המחיר עשוי להשתנות לפי אפשרויות.',
    price: 160.00,
    imageUrl: '/images/products/pkg11.jpeg',
    dataAiHint: 'spa bundle',
    category: 'חבילות',
    isActive: true,
  },
  {
    id: 'pkg12',
    name: 'מארז PerfumeClean X2',
    description: 'מארז משתלם של PerfumeClean. המחיר עשוי להשתנות לפי אפשרויות.',
    price: 110.00,
    imageUrl: '/images/products/pkg12.webp',
    dataAiHint: 'perfume clean bundle',
    category: 'חבילות',
    isActive: true,
  },

  // מוצרי ניקוי מקצועיים
  {
    id: 'kprof1',
    name: 'נוזל אורנים',
    description: 'נוזל ניקוי רב תכליתי בניחוח אורנים מרענן לניקוי משטחים. 1 ליטר.',
    price: 19.90,
    imageUrl: '/images/products/kprof1.jpeg',
    dataAiHint: 'pine cleaner',
    category: 'מוצרי ניקוי מקצועיים',
    isActive: true,
  },
  {
    id: 'kprof2',
    name: 'מנקה ומבריק שמשות ומשטחי זכוכית',
    description: 'מנקה ביעילות ומבריק משטחי זכוכית ושמשות, ללא סימנים. 750 מ"ל.',
    price: 25.00,
    imageUrl: '/images/products/kprof2.jpg',
    dataAiHint: 'glass cleaner',
    category: 'מוצרי ניקוי מקצועיים',
    isActive: true,
  },
  {
    id: 'kprof3',
    name: 'ניקוי והיגיינה למכונות כביסה',
    description: 'מנקה את מכונת הכביסה ביסודיות, מסיר אבנית ושומר על היגיינה. 1 ליטר.',
    price: 45.00,
    imageUrl: '/images/products/kprof3.jpg',
    dataAiHint: 'washing machine cleaner',
    category: 'מוצרי ניקוי מקצועיים',
    isActive: true,
  },
  {
    id: 'kprof4',
    name: 'חזק נגד שומנים קשים',
    description: 'מסיר שומנים עוצמתי לניקוי תנורים, כיריים ומשטחים עם שומן קשה במיוחד. 750 מ"ל.',
    price: 45.00,
    imageUrl: '/images/products/kprof4.jpeg',
    dataAiHint: 'grease remover',
    category: 'מוצרי ניקוי מקצועיים',
    isActive: true,
  },
  {
    id: 'kprof5',
    name: 'מסיר אבנית חלודה ולכלוך קשה',
    description: 'מסיר ביעילות אבנית, חלודה ולכלוך קשה מכלים סניטריים, ברזים ומשטחים. 1 ליטר.',
    price: 45.00,
    imageUrl: '/images/products/kprof5.jpg',
    dataAiHint: 'limescale remover',
    category: 'מוצרי ניקוי מקצועיים',
    isActive: true,
  },
  {
    id: 'kprof6',
    name: 'מנקה, מבריק משטחים , רהיטים ומשטחי פורמייקה',
    description: 'נוזל ייעודי לניקוי והברקת משטחים, רהיטים ופורמייקה, משאיר ניחוח נעים. 750 מ"ל.',
    price: 35.00,
    imageUrl: '/images/products/kprof6.jpg',
    dataAiHint: 'surface cleaner furniture',
    category: 'מוצרי ניקוי מקצועיים',
    isActive: true,
  },
  {
    id: 'kprof7',
    name: 'מסיר כתמים לפני כביסה',
    description: 'תרסיס עוצמתי להסרת כתמים קשים מבגדים לפני הכנסתם למכונת הכביסה. 750 מ"ל.',
    price: 40.00,
    imageUrl: '/images/products/kprof7.jpg',
    dataAiHint: 'stain remover prewash',
    category: 'מוצרי ניקוי מקצועיים',
    isActive: true,
  },

  // מפיצי ריח
  {
    id: 'kdf1',
    name: 'מפיץ ריח בניחוח כביסכל מאסק פלאוורס',
    description: 'מפיץ ריח איכותי (אירוסול) בניחוח מאסק פלאוורס של כביסכל. 250 מ"ל.',
    price: 25.00,
    imageUrl: '/images/products/kdf1.jpeg',
    dataAiHint: 'musk flowers diffuser',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf2',
    name: 'מפיץ ריח בניחוח כביסכל סופט קייר',
    description: 'מפיץ ריח עדין (אירוסול) בניחוח סופט קייר של כביסכל. 250 מ"ל.',
    price: 25.00,
    imageUrl: '/images/products/kdf2.jpeg',
    dataAiHint: 'soft care diffuser',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf3',
    name: 'מתקן מפיץ ריח אטומטי',
    description: 'מתקן אוטומטי להפצת ריח נעים בחלל החדר. מתאים למילויים סטנדרטיים.',
    price: 120.00,
    imageUrl: '/images/products/kdf3.jpeg',
    dataAiHint: 'automatic diffuser',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf4',
    name: 'מפיץ ריח בניחוח כביסכל רוז',
    description: 'מפיץ ריח קלאסי (אירוסול) בניחוח ורדים של כביסכל. 250 מ"ל.',
    price: 25.00,
    imageUrl: '/images/products/kdf4.jpeg',
    dataAiHint: 'rose diffuser',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf5',
    name: 'מפיץ ריח בניחוח כביסכל ארומטי',
    description: 'מפיץ ריח עשיר (אירוסול) בניחוח ארומטי של כביסכל. 250 מ"ל.',
    price: 25.00,
    imageUrl: '/images/products/kdf5.jpeg',
    dataAiHint: 'aromatic diffuser',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf6',
    name: 'מפיץ ריח בניחוח כביסכל בייבי',
    description: 'מפיץ ריח עדין במיוחד (אירוסול) בניחוח בייבי של כביסכל. 250 מ"ל.',
    price: 25.00,
    imageUrl: '/images/products/kdf6.jpeg',
    dataAiHint: 'baby diffuser',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf7',
    name: 'מפיץ ריח בניחוח כביסכל ספא',
    description: 'מפיץ ריח יוקרתי (אירוסול) בניחוח ספא של כביסכל. 250 מ"ל.',
    price: 25.00,
    imageUrl: '/images/products/kdf7.jpeg',
    dataAiHint: 'spa diffuser',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf8',
    name: 'דפיוזר מקלות שחורים – SILVER',
    description: 'דפיוזר עם מקלות שחורים בניחוח SILVER יוקרתי. 100 מ"ל.',
    price: 60.00,
    imageUrl: '/images/products/kdf8.png',
    dataAiHint: 'silver sticks diffuser',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf9',
    name: 'דפיוזר מקלות שחורים – GOLD',
    description: 'דפיוזר עם מקלות שחורים בניחוח GOLD יוקרתי. 100 מ"ל.',
    price: 60.00,
    imageUrl: '/images/products/kdf9.png',
    dataAiHint: 'gold sticks diffuser',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf10',
    name: 'דפיוזר מקלות שחורים – PLATINUM',
    description: 'דפיוזר עם מקלות שחורים בניחוח PLATINUM יוקרתי. 100 מ"ל.',
    price: 60.00,
    imageUrl: '/images/products/kdf10.png',
    dataAiHint: 'platinum sticks diffuser',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf11',
    name: 'דפיוזר מקלות שחורים – BRONZE',
    description: 'דפיוזר עם מקלות שחורים בניחוח BRONZE יוקרתי. 100 מ"ל.',
    price: 60.00,
    imageUrl: '/images/products/kdf11.png',
    dataAiHint: 'bronze sticks diffuser',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf12',
    name: 'מפיץ ריח פרח – וניל לבנדר פצ\'ולי',
    description: 'מפיץ ריח בצורת פרח בניחוח וניל, לבנדר ופצ\'ולי. 100 מ"ל.',
    price: 20.00,
    imageUrl: '/images/products/kdf12.jpg',
    dataAiHint: 'flower diffuser vanilla',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf13',
    name: 'מפיץ ריח פרח – וניל',
    description: 'מפיץ ריח בצורת פרח בניחוח וניל מתוק. 100 מ"ל.',
    price: 20.00,
    imageUrl: '/images/products/kdf13.jpg',
    dataAiHint: 'flower diffuser vanilla only',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf14',
    name: 'מפיץ ריח פרח – ילדותי',
    description: 'מפיץ ריח בצורת פרח בניחוח ילדותי ונעים. 100 מ"ל.',
    price: 20.00,
    imageUrl: '/images/products/kdf14.jpg',
    dataAiHint: 'flower diffuser kids',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf15',
    name: 'מפיץ ריח פרח – אושן בריז',
    description: 'מפיץ ריח בצורת פרח בניחוח אושן בריז מרענן. 100 מ"ל.',
    price: 20.00,
    imageUrl: '/images/products/kdf15.jpg',
    dataAiHint: 'flower diffuser ocean',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf16',
    name: 'מפיץ ריח פרח – למון גראס',
    description: 'מפיץ ריח בצורת פרח בניחוח למון גראס ממריץ. 100 מ"ל.',
    price: 20.00,
    imageUrl: '/images/products/kdf16.jpg',
    dataAiHint: 'flower diffuser lemongrass',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf17',
    name: 'מפיץ ריח פרח – בלאק אייס',
    description: 'מפיץ ריח בצורת פרח בניחוח בלאק אייס קריר. 100 מ"ל.',
    price: 20.00,
    imageUrl: '/images/products/kdf17.jpg',
    dataAiHint: 'flower diffuser blackice',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf18',
    name: 'מפיץ ריח פרח – זנזיבר',
    description: 'מפיץ ריח בצורת פרח בניחוח זנזיבר אקזוטי. 100 מ"ל.',
    price: 20.00,
    imageUrl: '/images/products/kdf18.jpg',
    dataAiHint: 'flower diffuser zanzibar',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kdf19',
    name: 'מפיץ ריח פרח – גולדן קאר',
    description: 'מפיץ ריח בצורת פרח בניחוח גולדן קאר יוקרתי. 100 מ"ל.',
    price: 20.00,
    imageUrl: '/images/products/kdf19.jpg',
    dataAiHint: 'flower diffuser goldencar',
    category: 'מפיצי ריח',
    isActive: true,
  },

  // מבשמים
  {
    id: 'kmb1',
    name: 'מבשם אלגנס 750 מ"ל',
    description: 'מבשם אריגים מרוכז בניחוח אלגנס קלאסי. מתאים לביגוד, וילונות וארונות.',
    price: 25.00,
    imageUrl: '/images/products/kmb1.jpeg',
    dataAiHint: 'elegance perfume',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb2',
    name: 'סופט קייר 750 מ"ל ביו',
    description: 'מבשם אריגים Bio עדין במיוחד בניחוח סופט קייר. מתאים לבעלי עור רגיש.',
    price: 25.00,
    imageUrl: '/images/products/kmb2.jpeg',
    dataAiHint: 'softcare perfume',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb3',
    name: 'פרידום 750 מ"ל',
    description: 'מבשם אריגים מרוכז בניחוח פרידום מרענן. מעניק תחושת חופש וניקיון.',
    price: 25.00,
    imageUrl: '/images/products/kmb3.jpeg',
    dataAiHint: 'freedom perfume',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb16',
    name: 'BRONZE – מבשם קפסולרי מרוכז 350 מ"ל',
    description: 'מבשם קפסולרי יוקרתי בניחוח BRONZE. טכנולוגיית שחרור מושהה לניחוח מתמשך.',
    price: 45.00,
    imageUrl: '/images/products/kmb16.png',
    dataAiHint: 'bronze capsule',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb17',
    name: 'PLATINUM – מבשם קפסולרי מרוכז 350 מ"ל',
    description: 'מבשם קפסולרי יוקרתי בניחוח PLATINUM. טכנולוגיית שחרור מושהה לניחוח מתמשך.',
    price: 45.00,
    imageUrl: '/images/products/kmb17.png',
    dataAiHint: 'platinum capsule',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb18',
    name: 'SILVER – מבשם קפסולרי מרוכז 350 מ"ל',
    description: 'מבשם קפסולרי יוקרתי בניחוח SILVER. טכנולוגיית שחרור מושהה לניחוח מתמשך.',
    price: 45.00,
    imageUrl: '/images/products/kmb18.png',
    dataAiHint: 'silver capsule',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb19',
    name: 'GOLD – מבשם קפסולרי מרוכז 350 מ"ל',
    description: 'מבשם קפסולרי יוקרתי בניחוח GOLD. טכנולוגיית שחרור מושהה לניחוח מתמשך.',
    price: 45.00,
    imageUrl: '/images/products/kmb19.png',
    dataAiHint: 'gold capsule',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb4',
    name: 'אוריינטל 750 מ"ל',
    description: 'מבשם אריגים מרוכז בניחוח אוריינטלי עשיר ומפנק.',
    price: 25.00,
    imageUrl: '/images/products/kmb4.jpeg',
    dataAiHint: 'oriental perfume',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb20',
    name: 'מבשם אוריינטל 350 מ"ל',
    description: 'מבשם אריגים מרוכז בניחוח אוריינטלי עשיר. גודל קומפקטי.',
    price: 16.00,
    imageUrl: '/images/products/kmb20.jpeg',
    dataAiHint: 'oriental perfume small',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb5',
    name: 'מבשם וניל 750 מ"ל',
    description: 'מבשם אריגים מרוכז בניחוח וניל מתוק וחמים.',
    price: 25.00,
    imageUrl: '/images/products/kmb5.jpeg',
    dataAiHint: 'vanilla perfume',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb21',
    name: 'מבשם ספא 350 מ"ל',
    description: 'מבשם אריגים מרוכז בניחוח ספא מרגיע. גודל קומפקטי.',
    price: 16.00,
    imageUrl: '/images/products/kmb21.jpeg',
    dataAiHint: 'spa perfume small',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb22',
    name: 'מבשם מאסק פלאוורס 350 מ"ל',
    description: 'מבשם אריגים מרוכז בניחוח מאסק ופרחים. גודל קומפקטי.',
    price: 16.00,
    imageUrl: '/images/products/kmb22.jpeg',
    dataAiHint: 'muskflowers perfume small',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb23',
    name: 'מבשם בוטיק סטייל 350 מ"ל',
    description: 'מבשם אריגים מרוכז בניחוח בוטיק יוקרתי. (אזל מהמלאי)',
    price: 16.00,
    imageUrl: '/images/products/kmb23.jpeg',
    dataAiHint: 'boutique perfume small',
    category: 'מבשמים',
    isActive: false,
  },
  {
    id: 'kmb6',
    name: 'ספא 750 מ"ל',
    description: 'מבשם אריגים מרוכז בניחוח ספא מרגיע ויוקרתי.',
    price: 25.00,
    imageUrl: '/images/products/kmb6.jpeg',
    dataAiHint: 'spa perfume',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb7',
    name: 'בייבי 750 מ"ל ביו',
    description: 'מבשם אריגים Bio היפואלרגני בניחוח עדין, מותאם לבגדי תינוקות.',
    price: 25.00,
    imageUrl: '/images/products/kmb7.jpeg',
    dataAiHint: 'baby perfume',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb8',
    name: 'אינוויקטוס 750 מ"ל',
    description: 'מבשם אריגים מרוכז בניחוח אינוויקטוס גברי ועוצמתי.',
    price: 25.00,
    imageUrl: '/images/products/kmb8.jpeg',
    dataAiHint: 'invictus perfume',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb9',
    name: 'לבנדר פרש 750 מ"ל',
    description: 'מבשם אריגים מרוכז בניחוח לבנדר רענן ומרגיע.',
    price: 25.00,
    imageUrl: '/images/products/kmb9.jpeg',
    dataAiHint: 'lavender perfume',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb10',
    name: 'ארומטי 750 מ"ל',
    description: 'מבשם אריגים מרוכז בניחוח ארומטי עשיר ומיוחד.',
    price: 25.00,
    imageUrl: '/images/products/kmb10.jpeg',
    dataAiHint: 'aromatic perfume',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb11',
    name: 'רוז 750 מ"ל',
    description: 'מבשם אריגים מרוכז בניחוח ורדים קלאסי ורומנטי.',
    price: 25.00,
    imageUrl: '/images/products/kmb11.jpeg',
    dataAiHint: 'rose perfume',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb12',
    name: 'רד רוז 750 מ"ל',
    description: 'מבשם אריגים מרוכז בניחוח ורד אדום עמוק וחושני.',
    price: 25.00,
    imageUrl: '/images/products/kmb12.jpeg',
    dataAiHint: 'redrose perfume',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb13',
    name: 'בוטיק סטייל 750 מ"ל',
    description: 'מבשם אריגים מרוכז בניחוח בוטיק יוקרתי ואלגנטי.',
    price: 25.00,
    imageUrl: '/images/products/kmb13.jpeg',
    dataAiHint: 'boutique perfume',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb14',
    name: 'מאסק פלאוורס 750 מ"ל',
    description: 'מבשם אריגים מרוכז בניחוח מאסק ופרחים משולב וקסום.',
    price: 25.00,
    imageUrl: '/images/products/kmb14.jpeg',
    dataAiHint: 'muskflowers perfume',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kmb15',
    name: 'וניל לבנדר פצ\'ולי 750 מ"ל',
    description: 'מבשם אריגים מרוכז בשילוב ניחוחות וניל, לבנדר ופצ\'ולי.',
    price: 25.00,
    imageUrl: '/images/products/kmb15.jpeg',
    dataAiHint: 'vanilla lavender patchouli',
    category: 'מבשמים',
    isActive: true,
  },

  // פרפלור מבשמי רצפות
  {
    id: 'kpff1',
    name: 'מבשם רצפות פרוביוטי מאסק פלאוורס',
    description: 'מבשם רצפות פרוביוטי מרוכז בניחוח מאסק פלאוורס. 1 ליטר.',
    price: 25.00,
    imageUrl: '/images/products/kpff1.jpeg',
    dataAiHint: 'floor freshener musk',
    category: 'פרפלור מבשמי רצפות',
    isActive: true,
  },
  {
    id: 'kpff2',
    name: 'מבשם רצפות פרקט ועץ רויאל',
    description: 'מבשם רצפות מיוחד לפרקט ועץ בניחוח רויאל יוקרתי. 1 ליטר.',
    price: 25.00,
    imageUrl: '/images/products/kpff2.jpeg',
    dataAiHint: 'floor freshener wood',
    category: 'פרפלור מבשמי רצפות',
    isActive: true,
  },
  {
    id: 'kpff3',
    name: 'מבשם רצפות פרוביוטי אלגנס',
    description: 'מבשם רצפות פרוביוטי מרוכז בניחוח אלגנס קלאסי. 1 ליטר.',
    price: 25.00,
    imageUrl: '/images/products/kpff3.jpeg',
    dataAiHint: 'floor freshener elegance',
    category: 'פרפלור מבשמי רצפות',
    isActive: true,
  },
  {
    id: 'kpff4',
    name: 'מבשם רצפות פרוביוטי בייבי',
    description: 'מבשם רצפות פרוביוטי עדין בניחוח בייבי, מתאים לחדרי ילדים. 1 ליטר.',
    price: 25.00,
    imageUrl: '/images/products/kpff4.jpeg',
    dataAiHint: 'floor freshener baby',
    category: 'פרפלור מבשמי רצפות',
    isActive: true,
  },
  {
    id: 'kpff5',
    name: 'מבשם רצפות פרוביוטי רוז',
    description: 'מבשם רצפות פרוביוטי מרוכז בניחוח ורדים רומנטי. 1 ליטר.',
    price: 25.00,
    imageUrl: '/images/products/kpff5.jpeg',
    dataAiHint: 'floor freshener rose',
    category: 'פרפלור מבשמי רצפות',
    isActive: true,
  },
  {
    id: 'kpff6',
    name: 'מבשם רצפות רד רוז',
    description: 'מבשם רצפות מרוכז בניחוח רד רוז עמוק וחושני. 1 ליטר.',
    price: 25.00,
    imageUrl: '/images/products/kpff6.jpeg',
    dataAiHint: 'floor freshener redrose',
    category: 'פרפלור מבשמי רצפות',
    isActive: true,
  },
  {
    id: 'kpff7',
    name: 'מבשם רצפות פרוביוטי ספא',
    description: 'מבשם רצפות פרוביוטי מרוכז בניחוח ספא מרגיע. 1 ליטר.',
    price: 25.00,
    imageUrl: '/images/products/kpff7.jpeg',
    dataAiHint: 'floor freshener spa',
    category: 'פרפלור מבשמי רצפות',
    isActive: true,
  },
  {
    id: 'kpff8',
    name: 'מבשם רצפות פרוביוטי ארומטי',
    description: 'מבשם רצפות פרוביוטי מרוכז בניחוח ארומטי עשיר. 1 ליטר.',
    price: 25.00,
    imageUrl: '/images/products/kpff8.jpeg',
    dataAiHint: 'floor freshener aromatic',
    category: 'פרפלור מבשמי רצפות',
    isActive: true,
  },

  // מגבונים
  {
    id: 'kwp1',
    name: 'מגבונים רכים לתינוק בניחוח סופט קייר',
    description: 'מגבונים עדינים במיוחד לתינוקות בניחוח סופט קייר. 72 יחידות.',
    price: 5.90,
    imageUrl: '/images/products/kwp1.jpeg',
    dataAiHint: 'baby wipes softcare',
    category: 'מגבונים',
    isActive: true,
  },
  {
    id: 'kwp2',
    name: 'מגבונים רכים לתינוק בניחוח בייבי',
    description: 'מגבונים עדינים במיוחד לתינוקות בניחוח בייבי הקלאסי. 72 יחידות.',
    price: 5.90,
    imageUrl: '/images/products/kwp2.jpeg',
    dataAiHint: 'baby wipes classic',
    category: 'מגבונים',
    isActive: true,
  },
  {
    id: 'kwp3',
    name: 'מארז מגבונים לחים ארומטי לניקוי כללי',
    description: 'מארז 3 חבילות מגבונים לניקוי כללי בניחוח ארומטי.',
    price: 22.90,
    imageUrl: '/images/products/kwp3.jpeg',
    dataAiHint: 'cleaning wipes aromatic',
    category: 'מגבונים',
    isActive: true,
  },
  {
    id: 'kwp4',
    name: 'מארז מגבונים לחים בייבי לניקוי כללי',
    description: 'מארז 3 חבילות מגבונים לניקוי כללי בניחוח בייבי עדין.',
    price: 22.90,
    imageUrl: '/images/products/kwp4.jpeg',
    dataAiHint: 'cleaning wipes baby',
    category: 'מגבונים',
    isActive: true,
  },
  {
    id: 'kwp5',
    name: 'מארז מגבונים לחים ספא לניקוי כללי',
    description: 'מארז 3 חבילות מגבונים לניקוי כללי בניחוח ספא יוקרתי.',
    price: 22.90,
    imageUrl: '/images/products/kwp5.jpeg',
    dataAiHint: 'cleaning wipes spa',
    category: 'מגבונים',
    isActive: true,
  },
  {
    id: 'kwp6',
    name: 'מארז מגבונים לחים רוז לניקוי כללי',
    description: 'מארז 3 חבילות מגבונים לניקוי כללי בניחוח רוז קלאסי.',
    price: 22.90,
    imageUrl: '/images/products/kwp6.jpeg',
    dataAiHint: 'cleaning wipes rose',
    category: 'מגבונים',
    isActive: true,
  },
  {
    id: 'kwp7',
    name: 'דלי מגבונים לניקוי כללי בניחוח ארומטי',
    description: 'דלי מגבונים (400 יח\') לניקוי כללי בניחוח ארומטי.',
    price: 35.00,
    imageUrl: '/images/products/kwp7.jpg',
    dataAiHint: 'bucket wipes aromatic',
    category: 'מגבונים',
    isActive: true,
  },
  {
    id: 'kwp8',
    name: 'דלי מגבונים לניקוי כללי בניחוח ספא',
    description: 'דלי מגבונים (400 יח\') לניקוי כללי בניחוח ספא.',
    price: 35.00,
    imageUrl: '/images/products/kwp8.jpg',
    dataAiHint: 'bucket wipes spa',
    category: 'מגבונים',
    isActive: true,
  },
  {
    id: 'kwp9',
    name: 'דלי מגבונים לניקוי כללי בניחוח בייבי',
    description: 'דלי מגבונים (400 יח\') לניקוי כללי בניחוח בייבי.',
    price: 35.00,
    imageUrl: '/images/products/kwp9.jpg',
    dataAiHint: 'bucket wipes baby',
    category: 'מגבונים',
    isActive: true,
  },
  {
    id: 'kwp10',
    name: 'דלי מגבונים לניקוי כללי בניחוח רוז',
    description: 'דלי מגבונים (400 יח\') לניקוי כללי בניחוח רוז.',
    price: 35.00,
    imageUrl: '/images/products/kwp10.jpg',
    dataAiHint: 'bucket wipes rose',
    category: 'מגבונים',
    isActive: true,
  },

  // נוזלי כלים
  {
    id: 'kds1',
    name: 'נוזל כלים פרוביוטי לבנדר פרש',
    description: 'נוזל כלים פרוביוטי מרוכז בניחוח לבנדר פרש מרענן. 750 מ"ל.',
    price: 16.50,
    imageUrl: '/images/products/kds1.jpg',
    dataAiHint: 'dish soap lavender',
    category: 'נוזלי כלים',
    isActive: true,
  },
  {
    id: 'kds2',
    name: 'נוזל כלים פרוביוטי אושן',
    description: 'נוזל כלים פרוביוטי מרוכז בניחוח אושן נקי ומרענן. 750 מ"ל.',
    price: 16.50,
    imageUrl: '/images/products/kds2.jpg',
    dataAiHint: 'dish soap ocean',
    category: 'נוזלי כלים',
    isActive: true,
  },
  {
    id: 'kds3',
    name: 'נוזל כלים פרוביוטי מאסק פלאוורס',
    description: 'נוזל כלים פרוביוטי מרוכז בניחוח מאסק פלאוורס קסום. 750 מ"ל.',
    price: 16.50,
    imageUrl: '/images/products/kds3.jpg',
    dataAiHint: 'dish soap musk',
    category: 'נוזלי כלים',
    isActive: true,
  },
  {
    id: 'kds4',
    name: 'נוזל כלים פרוביוטי ספא',
    description: 'נוזל כלים פרוביוטי מרוכז בניחוח ספא מרגיע ויוקרתי. 750 מ"ל.',
    price: 16.50,
    imageUrl: '/images/products/kds4.jpg',
    dataAiHint: 'dish soap spa',
    category: 'נוזלי כלים',
    isActive: true,
  },
  {
    id: 'pold1', 
    name: 'אבקת כביסה "כביסכל קלאסי הישן"',
    description: 'אבקת כביסה איכותית לכל סוגי הבדים, בניחוח מרענן. (מוצר ישן, לא פעיל)',
    price: 39.90,
    imageUrl: '/images/products/pold1.png', 
    dataAiHint: 'laundry powder',
    category: 'אבקות כביסה',
    isActive: false,
  },
];

export let placeholderOrders: Order[] = [
  {
    id: 'o1',
    customerName: 'ישראל ישראלי',
    customerPhone: '050-1234567',
    customerAddress: 'רחוב הראשי 1, תל אביב',
    items: [
      { productId: 'kbio1', productName: 'כביסכל Bio אלגנס – 2 ליטר', quantity: 2, priceAtOrder: 43.00 },
      { productId: 'kmb1', productName: 'מבשם אלגנס 750 מ"ל', quantity: 1, priceAtOrder: 25.00 },
    ],
    totalAmount: (43.00 * 2) + 25.00,
    orderTimestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
    status: 'new',
    isViewedByAgent: false,
  },
  {
    id: 'o2',
    customerName: 'שרה לוי',
    customerPhone: '052-7654321',
    customerAddress: 'שדרות הפרחים 5, ירושלים',
    customerNotes: 'נא להשאיר ליד הדלת אם אין מענה',
    items: [
      { productId: 'kbio2', productName: 'כביסכל Bio ספורט 2 ליטר', quantity: 1, priceAtOrder: 45.00 },
      { productId: 'kpff1', productName: 'מבשם רצפות פרוביוטי מאסק פלאוורס', quantity: 1, priceAtOrder: 25.00 },
    ],
    totalAmount: 45.00 + 25.00,
    orderTimestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // Two days ago
    status: 'completed',
    isViewedByAgent: true,
  },
  {
    id: 'o3',
    customerName: 'משה כהן',
    customerPhone: '054-1122333',
    customerAddress: 'דרך השלום 10, חיפה',
    items: [
      { productId: 'kprof1', productName: 'נוזל אורנים', quantity: 1, priceAtOrder: 19.90 },
      { productId: 'kds1', productName: 'נוזל כלים פרוביוטי לבנדר פרש', quantity: 2, priceAtOrder: 16.50 },
    ],
    totalAmount: 19.90 + (16.50 * 2),
    orderTimestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // Yesterday
    status: 'received', // Changed from 'new' to 'received' for variety
    isViewedByAgent: true, // Consistent with 'received'
  },
  {
    id: 'o4',
    customerName: 'דנה ברק',
    customerPhone: '053-9876543',
    customerAddress: 'הנשיא 20, באר שבע',
    items: [
      { productId: 'kmb16', productName: 'BRONZE – מבשם קפסולרי מרוכז 350 מ"ל', quantity: 1, priceAtOrder: 45.00 },
    ],
    totalAmount: 45.00,
    orderTimestamp: new Date(), // Today
    status: 'new',
    isViewedByAgent: false,
  },
];

// Function to allow service to modify placeholderProducts (for demo purposes)
export function setPlaceholderProducts(newProducts: Product[]) {
  placeholderProducts = newProducts;
}

export function addPlaceholderProduct(newProduct: Product) {
  placeholderProducts.push(newProduct);
}

export function updatePlaceholderProduct(updatedProduct: Product) {
  const index = placeholderProducts.findIndex(p => p.id === updatedProduct.id);
  if (index !== -1) {
    placeholderProducts[index] = updatedProduct;
  }
}

export function deletePlaceholderProduct(productId: string) {
  placeholderProducts = placeholderProducts.filter(p => p.id !== productId);
}


// Function to allow service to modify placeholderOrders (for demo purposes)
export function setPlaceholderOrders(newOrders: Order[]) {
  placeholderOrders = newOrders;
}

export function addPlaceholderOrder(newOrder: Order) {
  placeholderOrders.unshift(newOrder); // Add to the beginning to show newest first
}

export function updatePlaceholderOrder(updatedOrder: Order) {
  const index = placeholderOrders.findIndex(o => o.id === updatedOrder.id);
  if (index !== -1) {
    placeholderOrders[index] = updatedOrder;
  }
}

// Function to allow service to modify placeholderAdminUsers (for demo purposes)
// Note: In a real app, admin user management would be much more robust and secure.
export function setPlaceholderAdminUsers(newUsers: AdminUser[]) {
  // placeholderAdminUsers = newUsers; // This won't work as placeholderAdminUsers is const
  // Instead, clear the array and push new users
  while (placeholderAdminUsers.length > 0) {
    placeholderAdminUsers.pop();
  }
  newUsers.forEach(user => placeholderAdminUsers.push(user));
}

export function addPlaceholderAdminUser(newUser: AdminUser) {
  placeholderAdminUsers.push(newUser);
}

export function updatePlaceholderAdminUser(updatedUser: AdminUser) {
  const index = placeholderAdminUsers.findIndex(u => u.id === updatedUser.id);
  if (index !== -1) {
    placeholderAdminUsers[index] = updatedUser;
  }
}

export function deletePlaceholderAdminUser(userId: string) {
  const index = placeholderAdminUsers.findIndex(u => u.id === userId);
  if (index !== -1) {
    placeholderAdminUsers.splice(index, 1);
  }
}

