
import type { Product, Order } from './types';

export const placeholderProducts: Product[] = [
  // מוצרי ה- Bio שלנו
  {
    id: 'kbio1',
    name: 'כביסכל Bio אלגנס – 2 ליטר',
    description: 'נוזל כביסה Bio איכותי בניחוח אלגנס עדין.',
    price: 43.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'bio elegance',
    category: 'מוצרי ה- Bio שלנו',
    isActive: true,
  },
  {
    id: 'kbio2',
    name: 'כביסכל Bio ספורט 2 ליטר',
    description: 'נוזל כביסה Bio מותאם לבגדי ספורט, מנטרל ריחות.',
    price: 45.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'bio sport',
    category: 'מוצרי ה- Bio שלנו',
    isActive: true,
  },
  {
    id: 'kbio3',
    name: 'כביסכל Bio סופט קייר 2 ליטר',
    description: 'נוזל כביסה Bio עדין במיוחד, מתאים לבעלי עור רגיש.',
    price: 43.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'bio soft',
    category: 'מוצרי ה- Bio שלנו',
    isActive: true,
  },
  {
    id: 'kbio4',
    name: 'כביסכל Bio פרידום – 2 ליטר',
    description: 'נוזל כביסה Bio בניחוח מרענן של חופש.',
    price: 43.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'bio freedom',
    category: 'מוצרי ה- Bio שלנו',
    isActive: true,
  },
  {
    id: 'kbio5',
    name: 'כביסכל Bio אוריינטל – 2 ליטר',
    description: 'נוזל כביסה Bio בניחוח אוריינטלי עשיר ומפנק.',
    price: 43.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'bio oriental',
    category: 'מוצרי ה- Bio שלנו',
    isActive: true,
  },
  {
    id: 'kbio6',
    name: 'כביסכל Bio ספא – 2 ליטר',
    description: 'נוזל כביסה Bio בניחוח ספא מרגיע ויוקרתי.',
    price: 43.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'bio spa',
    category: 'מוצרי ה- Bio שלנו',
    isActive: true,
  },
  {
    id: 'kbio7',
    name: 'כביסכל Bio בייבי – 2 ליטר',
    description: 'נוזל כביסה Bio היפואלרגני, מותאם במיוחד לבגדי תינוקות.',
    price: 43.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'bio baby',
    category: 'מוצרי ה- Bio שלנו',
    isActive: true,
  },
  {
    id: 'kbio8',
    name: 'כביסכל Bio מאסק פלאורס – 2 ליטר',
    description: 'נוזל כביסה Bio בניחוח מאסק ופרחים משולב.',
    price: 43.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'bio musk',
    category: 'מוצרי ה- Bio שלנו',
    isActive: true,
  },
  {
    id: 'kbio9',
    name: 'כביסכל Bio רוז – 2 ליטר',
    description: 'נוזל כביסה Bio בניחוח ורדים קלאסי ורומנטי.',
    price: 43.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'bio rose',
    category: 'מוצרי ה- Bio שלנו',
    isActive: true,
  },
  {
    id: 'kbio10',
    name: 'כביסכל Bio ארומטי- 2 ליטר',
    description: 'נוזל כביסה Bio בניחוח ארומטי ועשיר.',
    price: 43.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'bio aromatic',
    category: 'מוצרי ה- Bio שלנו',
    isActive: true,
  },

  // קטגוריות נוספות
  {
    id: 'kcat1',
    name: 'מארז כביסה משתלם "כביסכל הכל כלול"',
    description: 'חבילה מושלמת הכוללת אבקה, ג\'ל ומרכך.',
    price: 120.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'laundry bundle',
    category: 'חבילות',
    isActive: true,
  },
  {
    id: 'kcat2',
    name: 'מבשם אריגים "בריזה קייצית"',
    description: 'מבשים אריגים לביגוד וארונות בניחוח קיץ מרענן.',
    price: 25.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'fabric freshener',
    category: 'מבשמים',
    isActive: true,
  },
  {
    id: 'kcat3',
    name: 'מגבונים לחים לניקוי כללי',
    description: 'מארז 100 מגבונים לחים לניקוי משטחים.',
    price: 15.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'wet wipes',
    category: 'מגבונים',
    isActive: true,
  },
  {
    id: 'kcat4',
    name: 'נוזל ניקוי רב תכליתי מקצועי',
    description: 'תרכיז נוזל ניקוי מקצועי למגוון שימושים.',
    price: 55.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'pro cleaner',
    category: 'מוצרי ניקוי מקצועיים',
    isActive: true,
  },
  {
    id: 'kcat5',
    name: 'מפיץ ריח אוטומטי "לבנדר"',
    description: 'מפיץ ריח חשמלי עם מילוי בניחוח לבנדר.',
    price: 70.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'air freshener',
    category: 'מפיצי ריח',
    isActive: true,
  },
  {
    id: 'kcat6',
    name: 'ספריי מפיץ ריח "אוקיינוס"',
    description: 'מפיץ ריח אירוסול בניחוח אוקיינוס מרענן.',
    price: 20.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'aerosol spray',
    category: 'מפיצי ריח אירוסולים',
    isActive: true,
  },
  {
    id: 'kcat7',
    name: 'נוזל כביסה קלאסי "כביסכל"',
    description: 'נוזל כביסה לשימוש יומיומי, יעיל וחסכוני.',
    price: 35.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'laundry liquid',
    category: 'נוזלי כביסה',
    isActive: true,
  },
  {
    id: 'kcat8',
    name: 'נוזל כלים "לימון וג\'ינג\'ר"',
    description: 'נוזל כלים מרוכז עם נוסחה פעילה להסרת שומנים.',
    price: 18.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dish soap',
    category: 'נוזלי כלים',
    isActive: true,
  },
  {
    id: 'kcat9',
    name: 'פרפלור מבשם רצפות "אביב"',
    description: 'מבשם רצפות מרוכז בניחוח אביבי ופרחוני.',
    price: 30.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'floor freshener',
    category: 'פרפלור מבשמי רצפות',
    isActive: true,
  },
   {
    id: 'pold1',
    name: 'אבקת כביסה "כביסכל קלאסי הישן"',
    description: 'אבקת כביסה איכותית לכל סוגי הבדים, בניחוח מרענן. (מוצר ישן, לא פעיל)',
    price: 39.90,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'laundry powder',
    category: 'אבקות כביסה',
    isActive: false, // Example of inactive product
  },
];

export const placeholderOrders: Order[] = [
  {
    id: 'o1',
    customerName: 'ישראל ישראלי',
    customerPhone: '050-1234567',
    customerAddress: 'רחוב הראשי 1, תל אביב',
    items: [
      { productId: 'kbio1', productName: 'כביסכל Bio אלגנס – 2 ליטר', quantity: 2, priceAtOrder: 43.00 },
      { productId: 'kcat2', productName: 'מבשם אריגים "בריזה קייצית"', quantity: 1, priceAtOrder: 25.00 },
    ],
    totalAmount: (43.00 * 2) + 25.00,
    orderTimestamp: new Date(Date.now() - 24 * 60 * 60 * 1000), // Yesterday
    status: 'new',
  },
  {
    id: 'o2',
    customerName: 'שרה לוי',
    customerPhone: '052-7654321',
    customerAddress: 'שדרות הפרחים 5, ירושלים',
    customerNotes: 'נא להשאיר ליד הדלת אם אין מענה',
    items: [
      { productId: 'kbio2', productName: 'כביסכל Bio ספורט 2 ליטר', quantity: 1, priceAtOrder: 45.00 },
    ],
    totalAmount: 45.00,
    orderTimestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // Two days ago
    status: 'processed',
  },
  {
    id: 'o3',
    customerName: 'משה כהן',
    customerPhone: '054-1122333',
    customerAddress: 'דרך השלום 10, חיפה',
    items: [
      { productId: 'kcat7', productName: 'נוזל כביסה קלאסי "כביסכל"', quantity: 1, priceAtOrder: 35.00 },
      { productId: 'kcat8', productName: 'נוזל כלים "לימון וג\'ינג\'ר"', quantity: 2, priceAtOrder: 18.00 },
    ],
    totalAmount: 35.00 + (18.00 * 2),
    orderTimestamp: new Date(),
    status: 'completed',
  },
];
